# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
{
  "dependencies": {
    "@azure/storage-blob": "^12.8.0",
    "@google-cloud/shell": "^1.0.5",
    "@google-cloud/trace-agent": "^5.1.6",
    "@gsensedev/gbanner": "^1.0.1",
    "@gsensedev/gbutton": "^1.0.0",
    "@gsensedev/gcard": "^1.0.0",
    "@gsensedev/gcardimage": "^1.0.0",
    "@gsensedev/gcol": "^1.0.0",
    "@gsensedev/ginput": "^1.0.0",
    "@gsensedev/grow": "^1.0.0",
    "@michael-f-bryan/gcode-wasm": "^0.6.1",
    "build": "^0.1.4",
    "cura-wasm": "^1.5.2",
    "expo-sqlite": "^9.2.1",
    "gcode-context": "^1.0.2",
    "gcode-file": "^1.0.6",
    "gcode-parser": "^1.3.7",
    "gs-luacat": "^0.2.3",
    "gs-redis-atomic-data-loader": "^1.1.3",
    "gs-utils": "^2.8.27",
    "history": "^5.0.1",
    "jshint": "^2.13.1",
    "lua-cc-tools": "^3.0.0",
    "node.js": "^0.0.1-security",
    "react-bootstrap": "^1.6.4",
    "react-create-use-store": "^3.1.1",
    "react-gcode-viewer": "^2.0.1",
    "react-native-webview": "^11.13.0",
    "react-router-config": "^5.1.1",
    "react-router-dom": "^5.3.0",
    "react-router-native": "^5.2.1",
    "react-router-redux": "^5.0.0-alpha.9",
    "redux-devtools-extension": "^2.13.9",
    "start": "^5.1.0",
    "vscode-extension-telemetry": "^0.4.4",
    "wget": "^0.0.1"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.15.8",
    "fengari-loader": "^0.0.1",
    "fengari-web": "^0.1.4",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.1",
    "react-proptypes-generate": "^1.7.6",
    "remote-redux-devtools": "^0.5.14",
    "remotedev-rn-debugger": "^0.8.4",
    "webpack": "^5.67.0",
    "webpack-cli": "^4.9.2"
  }
}
